services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: web_shop
    volumes:
      - ./src/main/resources/sql/create.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
